#ifndef SELINT_ERROR_H
#define SELINT_ERROR_H 

enum selint_error {
	SELINT_SUCCESS,
	SELINT_BAD_ARG,
	SELINT_OUT_OF_MEM,
	SELINT_NO_MOD_NAME,
	SELINT_NOT_IN_BLOCK,
	SELINT_IF_CALL_LOOP,
	SELINT_PARSE_ERROR,
	SELINT_M4_SUB_FAILURE,
	SELINT_CONFIG_PARSE_ERROR
};

#endif
